name: Update workout.xlsx via API

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Base64-encoded XLSX content'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Decode and write file
        run: |
          echo "${{ github.event.inputs.file }}" | base64 --decode > workout.xlsx

      - name: Commit workout.xlsx
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          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
          token: ${{ secrets.PAT_TOKEN }}
          commit_message: "Auto-update workout.xlsx"
          file_pattern: workout.xlsx
