name: Update workout.xlsx via API

on:
  workflow_dispatch:
    inputs:
      file:
        description: Base64-encoded XLSX content
        required: true

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    # 👉 expose the PAT to every step in the job
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Decode Base64 payload into workbook
      run: |
        echo "${{ github.event.inputs.file }}" | base64 --decode > workout.xlsx
        ls -l workout.xlsx

    - name: Commit & push workbook
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        add_options: -f                # force-add if already in .gitignore
        file_pattern: workout.xlsx
        commit_message: Auto-update workout.xlsx
