name: Update workout.xlsx via API

on:
  workflow_dispatch:
    inputs:
      file:
        description: Base64-encoded XLSX content
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Decode uploaded Excel
        run: |
          echo "${{ github.event.inputs.file }}" | base64 --decode > workout.xlsx

      - name: Commit workout.xlsx
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}   # <= your PAT
        with:
          commit_message: "Auto-update workout.xlsx"
          file_pattern: workout.xlsx
          add_options: -f

